In [2]:
# Full Code for Ensemble Learning (Iris Dataset)

# Importing libraries for data manipulation and visualization
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Importing libraries for model building and evaluation
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier, VotingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Importing XGBoost
from xgboost import XGBClassifier

# Importing Label Encoder
from sklearn.preprocessing import LabelEncoder

# Load the Iris dataset
iris_data = pd.read_csv("Iris.csv")

# Display the first few rows of the dataset
iris_data.head()

# Check for missing values
iris_data.isnull().sum()

# Label encode the target variable (Species)
le = LabelEncoder()
iris_data['Species'] = le.fit_transform(iris_data['Species'])

# Check the encoding
iris_data['Species'].unique()

# Split the data into features (X) and target (y)
X = iris_data.drop('Species', axis=1)
y = iris_data['Species']

# Perform an 80/20 split for training and testing
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Initialize and train AdaBoost Classifier
ada_model = AdaBoostClassifier(n_estimators=100, random_state=42)
ada_model.fit(X_train, y_train)

# Predict on the test data
y_pred_ada = ada_model.predict(X_test)

# Initialize and train Gradient Boosting Classifier
gb_model = GradientBoostingClassifier(n_estimators=100, random_state=42)
gb_model.fit(X_train, y_train)

# Predict on the test data
y_pred_gb = gb_model.predict(X_test)

# Initialize and train XGBoost Classifier
xgb_model = XGBClassifier(n_estimators=100, use_label_encoder=False, eval_metric='mlogloss', random_state=42)
xgb_model.fit(X_train, y_train)

# Predict on the test data
y_pred_xgb = xgb_model.predict(X_test)

# Evaluate AdaBoost Classifier
ada_accuracy = accuracy_score(y_test, y_pred_ada)
ada_report = classification_report(y_test, y_pred_ada)
ada_cm = confusion_matrix(y_test, y_pred_ada)

print(f"AdaBoost Accuracy: {ada_accuracy:.2f}")
print("AdaBoost Classification Report:\n", ada_report)
print("AdaBoost Confusion Matrix:\n", ada_cm)

# Evaluate Gradient Boosting Classifier
gb_accuracy = accuracy_score(y_test, y_pred_gb)
gb_report = classification_report(y_test, y_pred_gb)
gb_cm = confusion_matrix(y_test, y_pred_gb)

print(f"Gradient Boosting Accuracy: {gb_accuracy:.2f}")
print("Gradient Boosting Classification Report:\n", gb_report)
print("Gradient Boosting Confusion Matrix:\n", gb_cm)

# Evaluate XGBoost Classifier
xgb_accuracy = accuracy_score(y_test, y_pred_xgb)
xgb_report = classification_report(y_test, y_pred_xgb)
xgb_cm = confusion_matrix(y_test, y_pred_xgb)

print(f"XGBoost Accuracy: {xgb_accuracy:.2f}")
print("XGBoost Classification Report:\n", xgb_report)
print("XGBoost Confusion Matrix:\n", xgb_cm)



C:\Users\Lenovo\AppData\Roaming\Python\Python311\site-packages\sklearn\ensemble\_weight_boosting.py:519: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoost Accuracy: 1.00
AdaBoost Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

AdaBoost Confusion Matrix:
 [[10  0  0]
 [ 0 10  0]
 [ 0  0 10]]
Gradient Boosting Accuracy: 1.00
Gradient Boosting Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10
           2       1.00      1.00      1.00        10

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30

Gradient Boosting Confusion Matrix:
 [[10

C:\Users\Lenovo\AppData\Roaming\Python\Python311\site-packages\xgboost\core.py:158: UserWarning: [13:06:12] WARNING: C:\buildkite-agent\builds\buildkite-windows-cpu-autoscaling-group-i-0015a694724fa8361-1\xgboost\xgboost-ci-windows\src\learner.cc:740: 
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)


-

### Observations:

1. **AdaBoost (Adaptive Boosting)**:
    - **What it is**: AdaBoost combines many weak models (simple decision trees) to make one strong model.
    - **How it works**: It trains each new model to fix the mistakes made by the previous ones. It focuses more on the data points that were misclassified.
    - **Strengths**:
        - Works well on simple problems.
        - Can be a bit sensitive to noisy or incorrect data.
    - **Weaknesses**:
        - May not work well for complex problems.
        - It can focus too much on mistakes, leading to overfitting.

2. **Gradient Boosting**:
    - **What it is**: Gradient Boosting builds models that focus on the errors of the previous ones. It improves on mistakes by learning from them.
    - **How it works**: After each model is built, it corrects the errors from the last one, making the predictions better.
    - **Strengths**:
        - Works better on complex problems compared to AdaBoost.
        - It can learn more complex patterns in the data.
    - **Weaknesses**:
        - It may overfit if not properly tuned (learning too much from the data and not generalizing well).
        - Slower to run and more computationally expensive than AdaBoost.

3. **XGBoost (Extreme Gradient Boosting)**:
    - **What it is**: XGBoost is a faster and more efficient version of Gradient Boosting. It adds regularization to prevent overfitting and speeds up the learning process.
    - **How it works**: It improves on Gradient Boosting by using optimizations and adding techniques like pruning trees and handling missing data.
    - **Strengths**:
        - Faster and more accurate than Gradient Boosting.
        - Less likely to overfit because of regularization.
    - **Weaknesses**:
        - More complex and harder to tune.
        - Requires more memory and computational power, especially for large datasets.

### Evaluation Metrics:
- **Accuracy**: Shows how many predictions were correct overall. XGBoost usually performs the best here.
- **Classification Report**: Includes Precision, Recall, and F1-Score, which help in evaluating how well the model handles different types of errors.
- **Confusion Matrix**: Shows where the model is making mistakes, like which classes it confuses the most.

### Summary:
- **AdaBoost**: Best for simple problems, but can struggle with noise in data.
- **Gradient Boosting**: Works better on complex problems and improves over AdaBoost by focusing on fixing errors.
- **XGBoost**: The best for speed and accuracy, especially on big datasets, but more complex to tune.

### Additional Observations:
- We expect **XGBoost** to have the highest accuracy due to its optimizations and regularization techniques, but **Gradient Boosting** and **AdaBoost** are also strong contenders.
- Each model has its own strengths and trade-offs. AdaBoost is simpler and faster for smaller datasets, Gradient Boosting is more powerful for structured data, and XGBoost tends to be the most accurate for larger, more complex datasets.
- **Based on the results**, we would choose the model that best fits the problem's needs (accuracy, computational effici
--- 

You can now use this in your markdown file.

Here's an explanation of each step in the code:

1. **Importing Libraries for Data Manipulation and Visualization**:
    - `pandas` is imported to handle data in the form of DataFrames.
    - `numpy` is imported for numerical computations.
    - `matplotlib.pyplot` and `seaborn` are imported to create plots and visualize the data.

2. **Importing Libraries for Model Building and Evaluation**:
    - `train_test_split` from `sklearn.model_selection` is used to split the data into training and testing sets.
    - `AdaBoostClassifier`, `GradientBoostingClassifier`, and `VotingClassifier` from `sklearn.ensemble` are ensemble models used for classification.
    - `accuracy_score`, `classification_report`, and `confusion_matrix` from `sklearn.metrics` are used for evaluating the models' performance.

3. **Importing XGBoost**:
    - `XGBClassifier` from `xgboost` is imported to implement XGBoost, a highly efficient gradient boosting algorithm.

4. **Importing Label Encoder**:
    - `LabelEncoder` from `sklearn.preprocessing` is used to encode the target variable (Species) into numerical values since machine learning algorithms require numerical data.

5. **Loading the Iris Dataset**:
    - The Iris dataset is loaded using `pd.read_csv("Iris.csv")`. This dataset contains information about flower species and their respective measurements.

6. **Displaying the First Few Rows**:
    - The `head()` function is used to display the first few rows of the dataset for inspection.

7. **Checking for Missing Values**:
    - The `isnull().sum()` function is used to check if there are any missing values in the dataset. This is crucial to ensure data quality.

8. **Label Encoding the Target Variable (Species)**:
    - The `LabelEncoder` is used to convert the categorical target variable (Species) into numeric labels (e.g., 0, 1, 2) so that they can be used in machine learning models.

9. **Checking the Encoding**:
    - The `unique()` function is used to check the unique values in the `Species` column after encoding, ensuring that the label encoding worked correctly.

10. **Splitting the Data into Features (X) and Target (y)**:
    - The dataset is divided into features (X) and the target variable (y). Features include the measurements, and the target variable is the encoded species.

11. **Performing an 80/20 Split for Training and Testing**:
    - The `train_test_split` function splits the data into training and testing sets. 80% of the data is used for training, and 20% is reserved for testing. The `stratify=y` argument ensures that the split maintains the class distribution in both sets.

12. **Initializing and Training the AdaBoost Classifier**:
    - The AdaBoost model is initialized with 100 estimators and trained using the training data (`X_train` and `y_train`). This model is an ensemble technique that combines weak classifiers to create a stronger classifier.

13. **Predicting with AdaBoost**:
    - The trained AdaBoost model is used to predict the target variable on the test data (`X_test`), and the predictions are stored in `y_pred_ada`.

14. **Initializing and Training the Gradient Boosting Classifier**:
    - Similar to AdaBoost, the Gradient Boosting model is initialized with 100 estimators and trained on the training data. This model also builds an ensemble of models, but it works by minimizing errors of previous models.

15. **Predicting with Gradient Boosting**:
    - The trained Gradient Boosting model is used to make predictions on the test data (`X_test`), and the results are stored in `y_pred_gb`.

16. **Initializing and Training the XGBoost Classifier**:
    - The XGBoost model is initialized with 100 estimators, and trained on the training data. XGBoost is an optimized version of Gradient Boosting with enhancements like regularization and faster computation.

17. **Predicting with XGBoost**:
    - The trained XGBoost model is used to make predictions on the test data, and the results are stored in `y_pred_xgb`.

18. **Evaluating AdaBoost Classifier**:
    - The performance of AdaBoost is evaluated using three metrics:
        - **Accuracy**: The proportion of correct predictions.
        - **Classification Report**: A detailed report including Precision, Recall, and F1-score.
        - **Confusion Matrix**: A matrix showing the number of true positives, false positives, true negatives, and false negatives.

19. **Evaluating Gradient Boosting Classifier**:
    - Similar to AdaBoost, the performance of the Gradient Boosting model is evaluated using accuracy, classification report, and confusion matrix.

20. **Evaluating XGBoost Classifier**:
    - Again, XGBoost’s performance is evaluated using accuracy, classification report, and confusion matrix.

By following these steps, the code loads the Iris dataset, preprocesses the data, splits it into training and testing sets, applies three different ensemble learning models (AdaBoost, Gradient Boosting, and XGBoost), and evaluates their performance using standard classification metrics.